spring:
  application:
    name: game-client
#  cloud:
#    consul:
#      discovery:
#        enabled: false   #不作为服务，不用连接consul，获取服务实例列表

game:
  client:
    config:
      use-game-center: false
      game-center-url: http://localhost:5003/game-center-server
      