logging:
  config: file:config/log4j2.xml
# 115.28.208.195
#server:
#  port: 5003

#spring:
#  application:
#    name: game-center-server
#    desc: "游戏服务中心"
#  profiles:
#    active:
#      - wgs

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: my-game
#      password: xxx123456
#      authentication-database: admin
#      database: my-game
#  redis:
#    host: localhost
#    port: 6666
#    password: 123456

#  cloud:
#    consul:
#      host: 127.0.0.1
#      port: 7777
#      discovery:
#        instance-id: ${spring.application.name}:${server.port}
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
#        catalog-services-watch-delay: 10000