
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
#      username: my-game
#      password: 123456
#      authentication-database: admin
#      database: my-game
  redis:
    host: 127.0.0.1
    port: 6666
    password: 123456
