# server port有什么用？
server:
  port: 6002
spring:
  application:
    name: game-gateway
  redis:
    host: localhost
    port: 6666
    password: 123456
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        ip-address: 127.0.0.1
        register: true   #将游戏网关做为服务节点，注册到Consul上面。
        service-name: game-gateway  #注册到Consul上面的服务名称，用于区分此服务是否为游戏网关
#        instance-id: ${spring.application.name}:${server.port}
        health-check-ritical-timeout: 3000s
        tags:     # 可以自定义数据
          - gamePort=${game.gateway.server.config.port}  # 自定义数据，游戏网关的长连接端口
          - weight=3  # 游戏网关权重
        bus:
          enabled: true
        stream:
          kafka:
            binder:
              brokers:
                - localhost:9092  #配置Kafka地址
  # kafks是和cloud一个层级
  kafka:
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer  # 指定生产者的Key的序列化方式



management:
  endpoint:
    health:
      show-details: never
      
# 通过下边这样的方式，来一次性启动多个server实例
# 如果将port配置成不同的，将一次启动多个？这是为什么？
game:
  gateway:
    server:
      config:
        port: 6003  # 游戏网关的长连接端口，这里的数据是自定义配置。
        boss-thread-count: 1
        work-thread-count: 4
        server-id: 1001
        business-game-message-topic: business-game-message-topic # 向游戏服务发送消息 的Topic前缀
        gateway-game-message-topic: gateway-game-message-topic-${game.gateway.server.config.server-id} #接收游戏服务响应消息的Topic
#    config:
#      port: 6003  # 游戏网关的长连接端口，这里的数据是自定义配置。
#      boss-thread-count: 1
#      work-thread-count: 4
#      server-id: 1001
#      business-game-message-topic: business-game-message-topic # 向游戏服务发送消息 的Topic前缀
#      gateway-game-message-topic: gateway-game-message-topic-${game.gateway.server.config.server-id} #接收游戏服务响应消息的Topic