server:
  port: 5003
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: my-game
  redis:
    host: localhost
    port: 6666
    password: 123456
  application:
    name: game-center-server   #服务名称
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
        ip-address: 127.0.0.1
#        catalog-services-watch-delay: 10000


management:
  endpoint:
    health:
      show-details: never